language: cpp
dist: focal
compiler: gcc

git:
  submodules: false

install:
  - sudo apt-get -y install -y libsdl2-dev
  - sudo apt-get -y install -y libsdl2-image-dev
  - sudo apt-get -y install -y libsdl2-mixer-dev
  - sudo apt-get -y install -y libzip-dev

script:
  - make
  - ./bin/pekka-kana-2 version